---
# tasks file for system-config
- name: install system packages
  pacman: 
    name:
      - acpi
      - at
      - bluez
      - bluez-firmware
      - bluez-libs
      - bluez-utils
      - lsb-release
      - sudo
    # - chrony
      - iptables
      - nftables
    state: present

- name: passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

# - name: blacklist modules
# - name: audio config

