---
# tasks file for system-config
- name: enable multilib repo
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: install system packages
  pacman: 
    name:
      - efibootmgr
      - syslinux
      - bash
      - zsh
      - bash-completion
      - git
      - acpi
      - at
      - bluez
      - bluez-firmware
      - bluez-libs
      - bluez-utils
      - usbutils
      - lsb-release
      - sudo
      - openssh
      - openssh-askpass
      - dhcpcd
      - dmidecode
    # - chrony
      - iptables
      - ipset
      - nftables
      - ebtables
      - os-prober
      - cups
      - cups-pdf
      - gpm
      - samba
      - ntfs-3g
      - texinfo
      - openntpd
      - nfs-utils
    update_cache: yes
    state: present

- name: passwordless sudo
  lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: bash-completions directory
  file:
    path: "/etc/bash-completion.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: /mnt directories
  file:
    path: "/mnt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - usb
    - usb2
    - usb3
    - usb4

## audio configuration

- name: install audio packages
  pacman: 
    name:
      - alsa-utils
      - alsa-plugins
      - alsa-oss
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pavucontrol
    state: present

## this is not recommended by archwiki
## consider if it's needed or not
- name: add laptop_user to the audio group
  user:
    name: "{{ laptop_user }}"
    groups: audio
    append: yes


## Time

- name: set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid
  when: ansible_facts['date_time']['tz'] == "UTC"

- name: enable and start openntpd
  service:
    name: openntpd
    state: started
    enabled: yes


## Samba is not enabled by default
## This is just to share between VMs when needed
- name: samba configuration to share $HOME
  template:
    src: smb.conf.j2
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: 0644

## blacklist modules
