---
# tasks file for editors
- name: install editor packages
  pacman: 
    name:
      - vim
      - neovim
      - code
      - atom
      - kakoune
      - retext
      - texlive-bin
    state: present

- name: install editor packages from AUR
  block:
  - name: install vim plugins
    yay:
      name:
        - vim-csv-git
        - vim-go
        - vim-iptables
        - vim-puppet
        - vim-rainbow-parentheses-git
        - vim-vimwiki
      state: present
  - name: install editors
    yay:
      name:
        - remarkable
      state: present
  become: false

- name: copy vim config
  copy:
    src: vimrc
    dest: "/home/{{ laptop_user }}/.vimrc"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644

- name: install code extensions
  block:
  - name: list installed code extensions
    command: "code --list-extensions"
    register: code_extensions

  - name: add code extensions
    command: "code --install-extension {{ item }}"
    loop: "{{ editors.code_extensions }}"
    when: item not in code_extensions.stdout_lines
  become_user: "{{ laptop_user }}"
