---
# tasks file for multimedia
- name: install multimedia packages
  pacman:
    name:
      - mplayer
      - vlc
      - ffmpeg
      - mencoder
      - minidlna
      - mp3info
      - mpg123
      - handbrake
      - handbrake-cli
      - gstreamer
      - gst-plugins-base
      - gst-plugins-base-libs
      - gst-plugins-good
      - gst-plugins-bad
      - audacity
      - cheese
      - cmus
      - gimp
      - mcomix
      - yed
    state: present
