---
# tasks file for multimedia
- name: install multimedia packages
  pacman:
    name:
      - mplayer
      - vlc
      - ffmpeg
      - mencoder
      - minidlna
      - mp3info
      - mpg123
      - handbrake
      - handbrake-cli
      - gstreamer
      - gst-plugins-base
      - gst-plugins-base-libs
      - gst-plugins-good
      - gst-plugins-bad
      - audacity
      - cheese
      - cmus
      - gimp
      - imagemagick
      - mcomix
      - dia
      - openshot
      - rtorrent
      - byzanz
      - recordmydesktop
      - rtmpdump
      - cdparanoia
    state: present

- name: install multimedia packages from AUR
  yay:
    name:
      - audio-recorder
      - mp3gain
      - yed
    state: present
  become: false

- name: copy rtorrent config file
  template:
    src: rtorrent.rc.j2
    dst: "/home/{{ laptop_user }}/.rtorrent.rc"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644
