---
# tasks file for multimedia
- name: install multimedia packages
  pacman:
    name:
      - mplayer
      - vlc
      - ffmpeg
      - mencoder
      - minidlna
      - mp3info
      - mpg123
      - handbrake
      - handbrake-cli
      - gstreamer
      - gst-plugins-base
      - gst-plugins-base-libs
      - gst-plugins-good
      - gst-plugins-bad
      - audacity
      - cheese
      - cmus
      - gimp
      - imagemagick
      - mcomix
      - dia
      - yed
      - openshot
      - rtorrent
    state: present

- name: install multimedia packages from AUR
  yay:
    name:
      - audio-recorder
    state: present
  become: false
