---
# tasks file for cloud
- name: install cloud cli
  pacman:
    name:
      - aws-cli
    state: present

- name: install cloud cli from AUR
  yay:
    name:
      - google-cloud-sdk
      - python-azure-cli
      - ibmcloud-cli
    state: present
  become: false
