---
# tasks file for games
- name: install games packages
  pacman:
    name:
      - gnugo
      - qgo
      - nethack
      - scratch
      - critter
      - tuxpaint
      - stone-soup
    state: present

- name: install games from AUR
  yay: 
    name:
      - cgoban3
      - gopanda
      - gogui
      - sabaki
      - koules
      - egoboo
      - spectemu
      - xaos
    state: present
  become: false

- name: alias for sabaki
  lineinfile:
    path: "/home/{{ laptop_user }}/.bashrc"
    line: 'alias sabaki=/opt/Sabaki/sabaki"
    state: present
