---
# tasks file for games
- name: install games packages
  pacman:
    name:
      - gnugo
      - qgo
    state: present

- name: install games from AUR
  yay: 
    name:
      - cgoban3
#     - maelstrom
    state: present
  become: false
