---
# tasks file for games
- name: install games packages
  pacman:
    name:
      - gnugo
      - qgo
      - nethack
      - scratch
      - critter
      - tuxpaint
      - stone-soup
      - xbill
    state: present

- name: install games from AUR
  yay: 
    name:
      - cgoban3
      - egoboo
      - gogui
      - koules
      - spectemu
      - xaos
    state: present
  become: false
