---
# tasks file for window-manager
- name: install wm packages
  pacman:
    name:
      - i3-wm
      - dmenu
      - i3lock
      - i3status
      - wayland
      - wayland-protocols
      - sway
      - swaylock
      - wl-clipboard 
      - grim
    state: present

- name: create sway/i3 config directories
  file:
    path: "/home/{{ laptop_user }}/.config/{{ item }}"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0755
  loop:
    - sway
    - i3

- name: sway/i3 config files
  copy:
    src: "{{ item }}_config"
    dest: "/home/{{ laptop_user }}/.config/{{ item }}/config"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644
  loop:
    - sway
    - i3

- name: Xdefaults file
  copy:
    src: Xdefaults
    dest: "/home/{{ laptop_user }}/.Xdefaults"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644

- name: xserverrc file
  copy:
    src: xserverrc
    dest: "/home/{{ laptop_user }}/.xserverrc"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644

- name: add fonts packages from official and AUR
  yay:
    name:
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-freefont
      - ttf-hanazono
      - ttf-inconsolata
      - ttf-liberation
      - ttf-linux-libertine
      - ttf-sazanami
      - ttf-ubuntu-font-family
      - ttf-windows
    state: present
  become: false

- name: copy local fonts
  copy:
    src: fonts
    dest: "/home/{{ laptop_user }}/.fonts"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644
    directory_mode: 0755

