---
# tasks file for window-manager
- name: install wm packages
  pacman:
    name:
      - i3lock
      - i3status
      - wayland
      - wayland-protocols
      - sway
      - grim
    state: present

- name: create config directory
  file:
    path: "/home/{{ laptop_user }}/.config/sway"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0755

- name: sway config file
  copy:
    src: config
    dest: .config/sway/config
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644

- name: Xdefaults file
  copy:
    src: Xdefaults
    dest: .Xdefaults
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644

- name: add fonts packages from official and AUR
  yay:
    name:
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-freefont
      - ttf-hanazono
      - ttf-inconsolata
      - ttf-liberation
      - ttf-linux-libertine
      - ttf-sazanami
      - ttf-ubuntu-font-family
      - ttf-windows
    state: present
  become: false
