---
# tasks file for base-tools
- name: install base tools
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - zathura
    - zathura-djvu
    - zathura-pdf-mupdf
    - feh
    - gcc
    - dos2unix
    - zip
    - afpfs-ng
    - bc
    - bind-tools
    - cowsay
