---
# tasks file for base-tools
- name: install base tools
  pacman:
    name:
      - git
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
      - ghostscript
      - feh
      - gcc
      - dos2unix
      - zip
      - afpfs-ng
      - bc
      - bind-tools
      - cowsay
      - jq
      - xmlstarlet
      - sl
      - lsof
      - sl
    state: present

- name: install base tools from AUR
  yay:
    name:
      - mmv
      - apg
    state: present
  become: false
