---
# tasks file for base-tools
- name: install base tools
  pacman:
    name:
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
      - ghostscript
      - evince
      - calibre
      - feh
      - gcc
      - dos2unix
      - zip
      - unzip
      - unrar
      - p7zip
      - afpfs-ng
      - bc
      - cowsay
      - jq
      - xmlstarlet
      - sl
      - lsof
      - sl
      - dosfstools
      - mtools
      - smbclient
      - putty
      - rdesktop
      - freerdp
    # - winexe
      - rsync
      - gtop
      - testdisk
      - cdrdao
      - cdrtools
      - brasero
      - dvd+rw-tools
      - tree
      - uudeview
      - fzf
      - task
    state: present

- name: install base tools from AUR
  yay:
    name:
    # - mmv
      - apg
      - pwsafe
      - gopass
    # - toilet
    # - toilet-fonts
      - stapler
      - pdftk-bin
      - impressive
    state: present
  become: false
