---
# tasks file for config-management
- name: install configuration management tools
  pacman:
    name:
      - puppet
      - hiera
      - ansible
      - salt
      - terraform
      - fabric
      - expect
    state: present

- name: install configuration management tools
  yay:
    name:
      - puppet-bolt
      - pdk
    state: present
  become: false
