---
# tasks file for config-management
- name: install configuration management tools
  pacman:
    name:
      - puppet
      - hiera
      - ansible
      - salt
      - terraform
      - fabric
      - expect
    state: present

- name: install configuration management tools
  yay:
    name:
      - puppet-bolt
      - pdk
      - openpolicyagent-bin
   #  - conftest
    state: present
  become: false

- name: install config management gems
  gem:
    name: "{{ item }}"
    user_install: no
    state: present
  loop:
    - puppet_litmus
    - rspec-puppet
    - inspec-bin
