---
# tasks file for programming
- name: install programming languages and tools
  pacman:
    name:
      - go
      - clojure
      - ruby
      - ruby-irb
      - rubygems
      - rbenv
      - jruby
      - ipython
      - jupyter
      - rust
      - lua
      - autoconf
      - automake
      - cmake
      - maven
      - bison
      - ghc
      - nodejs
      - npm
      - yarn
      - subversion
      - mercurial
      - ocaml
    state: present

- name: install programming languages and tools from AUR
  yay:
    name:
      - leiningen
      - leiningen-completions
    state: present
  become: false
