---
# tasks file for programming
- name: install programming languages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - clojure
    - ruby
    - ruby-irb
    - rubygems
    - jruby
    - rust
    - lua
    - autoconf
    - automake
    - cmake
