---
# tasks file for browsers
- name: install official repo browsers
  pacman: 
    name:
      - firefox
      - links
      - lynx
      - curl
      - wget
      - icedtea-web
      - httpie
      - http-parser
    state: present

- name: install browsers from AUR
  yay:
    name:
      - google-chrome-beta
      - google-talk-plugin
      - postman-bin
      - insomnia
    state: present
  become: false
