---
# tasks file for browsers
- name: install official repo browsers
  pacman: 
    name:
      - firefox
      - links
      - lynx
      - curl
      - wget
      - icedtea-web
      - flashplugin
      - httpie
      - http-parser
      - min
      - w3m
    state: present

- name: install browsers from AUR
  yay:
    name:
      - google-chrome-beta
      - google-talkplugin
      - postman-bin
      - insomnia
    state: present
  become: false
