---
# tasks file for containers
- name: install container packages
  pacman:
    name:
      - docker
      - docker-compose
      - docker-machine
      - runc
      - containerd
      - skopeo
    state: present

- name: enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add laptop_user to the docker group
  user:
    name: "{{ laptop_user }}"
    groups: docker
    append: yes

- name: add some basic images
  docker_image:
    name: "{{ item }}"
  loop:
    - centos:latest
    - debian:latest
    - alpine:latest

- name: install AUR container packages
  yay:
    name:
      - docker-machine-driver-kvm2
      - kubectl-bin
      - kustomize-bin
      - kubernetes-helm-bin
      - kops-bin
      - minikube
      - kubectx
      - k9s-bin
      - origin-client-bin
      - minishift-bin
    state: present
  become: false

- name: add bash completion for k8s
  shell: kubectl completion bash > /etc/bash-completion.d/kubectl

- name: add kubectl aliases file
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
    dest: "/home/{{ laptop_user }}/.kubectl_aliases"
    mode: 0466

- name: ensure .kubectl-aliases is sourced in .bashrc
  lineinfile:
    path: "/home/{{ laptop_user }}/.bashrc"
    line: "source ~/.kubectl-aliases"

- name: install script to ensure alias are tab-completed
  get_url:
    url: https://raw.githubusercontent.com/cykerway/complete-alias/master/bash_completion.sh
    dest: "/home/{{ laptop_user }}/bin/bash_completion.sh"
    mode: 0466

- name: ensure bash_completion.sh is sourced in .bashrc
  lineinfile:
    path: "/home/{{ laptop_user }}/.bashrc"
    line: "source ~/bin/bash_completion.sh"

- name: add kubectl aliases to be tab-completed
  blockinfile:
    path: "/home/{{ laptop_user }}/.bashrc"
    block: |
      for _a in $(sed '/^alias /!d;s/^alias //;s/=.*$//' ~/.kubectl_aliases); do
        complete -F _complete_alias "$_a"
      done
