---
# tasks file for containers
- name: install container packages
  pacman:
    name:
      - docker
      - docker-compose
      - docker-machine
      - runc
      - containerd
    state: present

- name: enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add laptop_user to the docker group
  user:
    name: "{{ laptop_user }}"
    groups: docker
    append: yes

- name: add some basic images
  docker_image:
    name: "{{ item }}"
  loop:
    - centos:latest
    - debian:latest
    - alpine:latest

- name: install AUR container packages
  yay:
    name:
      - docker-machine-driver-kvm2
      - kubectl-bin
      - kustomize-bin
      - kubernetes-helm-bin
      - kops-bin
      - minikube
      - k9s-bin
      - origin-client-bin
      - minishift-bin
    state: present
  become: false
