---
# tasks file for virtualization
- name: install virtualization packages
  pacman:
    name:
      - bridge-utils
      - qemu
      - libvirt
      - virt-install
      - virt-manager
      - virt-viewer
      - virtualbox
      - vagrant
      - openvswitch
      - pkgconf
      - wine
      - packer
    state: present

- name: enable and start libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: add laptop_user to the virtualization groups
  user:
    name: "{{ laptop_user }}"
    groups: libvirt,vboxusers
    append: yes

- name: install vagrant plugins
  block:
  - name: list installed vagrant plugins
    command: "vagrant plugin list"
    register: vagrant_plugins
  - name: add vagrant plugins
    command: "vagrant plugin install {{ item }}"
    loop: "{{ virtualization.vagrant_plugins }}"
    when: item not in "{{ vagrant_plugins.stdout_lines }}"
  become_user: "{{ laptop_user }}"

# - name: install vagrant plugins
#   block:
#   - name: check if vagrant-libvirt is installed
#     shell: vagrant plugin list | grep -q vagrant-libvirt
#     ignore_errors: yes
#     register: vagrant_libvirt
#   - name: install vagrant-libvirt
#     command: "vagrant plugin install vagrant-libvirt"
#     when: vagrant_libvirt.rc != 0
#   - name: check if vagrant-libvirt is installed
#     shell: vagrant plugin list | grep -q vagrant-hostmanager
#     ignore_errors: yes
#     register: vagrant_hostmanager
#   - name: install vagrant-libvirt
#     command: "vagrant plugin install vagrant-hostmanager"
#     when: vagrant_hostmanager.rc != 0
#   - name: check if vagrant-mutate is installed
#     shell: vagrant plugin list | grep -q vagrant-mutate
#     ignore_errors: yes
#     register: vagrant_mutate
#   - name: install vagrant-mutate
#     command: "vagrant plugin install vagrant-mutate"
#     when: vagrant_mutate.rc != 0
#   become_user: "{{ laptop_user }}"

# - name: install virtualization packages from AUR
#   yay:
#     name:
#       - libguestfs
#     state: present
#   become: false
