---
# tasks file for virtualization
- name: install virtualization packages
  pacman:
    name:
      - libvirt
      - qemu
      - virtualbox
      - vagrant
      - openvswitch
      - pkgconf
    state: present

- name: enable and start libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: add laptop_user to the virtualization groups
  user:
    name: "{{ laptop_user }}"
    groups: libvirt,vboxusers
    append: yes

- name: install vagrant plugins
  block:
  - name: check if vagrant-libvirt is installed
    shell: vagrant plugin list | grep -q vagrant-libvirt
    register: vagrant_libvirt
  - name: install vagrant-libvirt
    command: "vagrant plugin install vagrant-libvirt"
    when: vagrant_libvirt.rc != 0
  - name: check if vagrant-libvirt is installed
    shell: vagrant plugin list | grep -q vagrant-hostmanager
    register: vagrant_hostmanager
  - name: install vagrant-libvirt
    command: "vagrant plugin install vagrant-hostmanager"
    when: vagrant_hostmanager.rc != 0
  become: false
