---
# tasks file for virtualization
- name: install virtualization packages
  pacman:
    name:
      - bridge-utils
      - qemu
      - libvirt
      - virt-install
      - virt-manager
      - virt-viewer
      - virtualbox
      - vagrant
      - openvswitch
      - pkgconf
      - wine
      - packer
    state: present

- name: enable and start libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: add laptop_user to the virtualization groups
  user:
    name: "{{ laptop_user }}"
    groups: libvirt,vboxusers
    append: yes

- name: install vagrant plugins
  block:
  - name: list installed vagrant plugins
    shell: "vagrant plugin list | awk '{ print $1 }'"
    register: vagrant_plugins
  - name: add vagrant plugins
    command: "vagrant plugin install {{ item }}"
    loop: "{{ virtualization.vagrant_plugins }}"
    when: item not in vagrant_plugins.stdout_lines
  become_user: "{{ laptop_user }}"


- name: sudoers config for vagrant plugins
  template:
    src: sudoers-vagrant_hostmanager2.j2
    dest: /etc/sudoers.d/vagrant_hostmanager2
    owner: root
    group: root
    mode: 0640

- name: sudoers config for vagrant plugins
  copy:
    src: sudoers-vagrant_nfs
    dest: /etc/sudoers.d/vagrant_nfs
    owner: root
    group: root
    mode: 0640

# - name: install virtualization packages from AUR
#   yay:
#     name:
#       - libguestfs
#     state: present
#   become: false
