---
# tasks file for network-tools
- name: install network tools packages
  pacman:
    name:
      - net-tools
      - socat
      - tsocks
      - openvpn
      - wireshark-cli
      - wireshark-qt
      - dnstracer
      - lftp
      - atftp
      - curlftpfs
      - sshfs
      - dnsmasq
      - fping
      - mtr
      - ethtool
      - bind-tools
      - ipcalc
      - ipv6calc
      - iptraf-ng
      - traceroute
      - whois
      - openldap
      - tcpdump
      - sshuttle
    state: present

- name: install network tools from AUR
  yay: 
    name:
      - tcptraceroute
      - apache-tools
      - ubridge
      - bing
      - termshark-bin
    # - dynamips 
    # - gns3-server # conflict of python libraries
    # - gns3-gui
    state: present
  become: false
