---
# tasks file for network-tools
- name: install network tools packages
  pacman:
    name:
      - net-tools
      - socat
      - openvpn
      - wireshark-cli
      - wireshark-common
      - wireshark-gtk
      - dnstracer
      - lftp
      - atftp
      - curlftpfs
      - dnsmasq
      - fping
      - bing
      - mtr
      - ethtool
      - bind-tools
      - ipcalc
      - ipv6calc
      - iptraf-ng
      - traceroute
      - whois
      - openldap
      - tcpdump
    state: present

- name: install network tools from AUR
  yay: 
    name:
      - tcptraceroute
      - apache-tools
      - ubridge
      - dynamips
      - gns3-server
      - gns3-gui
    state: present
  become: false
