---
# tasks file for home-config
- name: Create home directory structure
  file:
    path: "/home/{{ laptop_user }}/{{ item }}"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0755
  loop:
    - bin
    - docs
    - downloads
    - personal/projects
    - pictures
    - software/system
    - misc
    - tmp
