---
# tasks file for home-config
- name: create home directory structure
  file:
    path: "/home/{{ laptop_user }}/{{ item }}"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0755
  loop:
    - bin
    - docs
    - downloads
    - misc
    - personal/projects
    - pictures
    - software/containers
    - software/games
    - software/networking
    - software/system
    - software/vagrant
    - software/vbox
    - tmp

- name: create work directory structure
  file:
    path: "/home/{{ laptop_user }}/{{ current_employer }}/{{ item }}"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0755
  loop:
    - code
    - config
    - learning
    - misc
    - projects
    - sales/presentations

- name: create some dot directories structure
  file:
    path: "/home/{{ laptop_user }}/{{ item }}"
    state: directory
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0700
  loop:
    - .ssh
    - .gnupg

- name: copy gpg-agent config file
  copy:
    src: "{{ item }}"
    dest: "/home/{{ laptop_user }}/.gnupg/{{ item }}"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0640
  loop:
    - gpg-agent.conf

- name: copy dot-files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ laptop_user }}/.{{ item }}"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0640
  loop:
    - bashrc

- name: add home bin files
  copy:
    src: bin
    dest: "/home/{{ laptop_user }}/"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0750
