---
# tasks file for terminals
- name: install terminal packages
  pacman:
    name: 
      - xterm
      - termite 
      - kitty
      - tmux
    state: present

- name: install terminal packages from AUR
  yay:
    name:
      - console-solarized-git
      - terminus-terminal-bin
      - st
    state: present
  become: false

- name: copy termite config
  copy:
    src: termite.config
    dest: "/home/{{ laptop_user }}/.config/termite/config"
    owner: "{{ laptop_user }}"
    group: "{{ laptop_user }}"
    mode: 0644
