---
# tasks file for terminals
- name: install terminal packages
  pacman:
    name: 
      - xterm
      - termite 
      - kitty
      - st
    state: present

- name: install terminal packages from AUR
  yay:
    name:
      - console-solarized-git
      - terminus-terminal-bin
    state: present
  become: false
